VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "btnDirectory"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Private Sub AirfieldPurchase_Click()
    Call modGameLogic.AirfieldPurchase
End Sub

Private Sub AmmoShopPortal_Click()
    Call modGameLogic.AmmoShopPortal
End Sub

Private Sub BT01_Click()
    Call modGameLogic.BT01
End Sub

Private Sub BT02_Click()
    Call modGameLogic.BT02
End Sub

Private Sub BT03_Click()
    Call modGameLogic.BT03
End Sub

Private Sub BT04_Click()
    Call modGameLogic.BT04
End Sub

Private Sub BT05_Click()
    Call modGameLogic.BT05
End Sub

Private Sub BT06_Click()
    Call modGameLogic.BT06
End Sub

Private Sub BT07_Click()
    Call modGameLogic.BT07
End Sub

Private Sub BT08_Click()
    Call modGameLogic.BT08
End Sub

Private Sub BT09_Click()
    Call modGameLogic.BT09
End Sub

Private Sub BT10_Click()
    Call modGameLogic.BT10
End Sub

Private Sub BT11_Click()
    Call modGameLogic.BT11
End Sub

Private Sub BT12_Click()
    Call modGameLogic.BT12
End Sub

Private Sub BT13_Click()
    Call modGameLogic.BT13
End Sub

Private Sub BT14_Click()
    Call modGameLogic.BT14
End Sub

Private Sub BT15_Click()
    Call modGameLogic.BT15
End Sub

Private Sub BT16_Click()
    Call modGameLogic.BT16
End Sub

Private Sub BT17_Click()
    Call modGameLogic.BT17
End Sub

Private Sub BT18_Click()
    Call modGameLogic.BT18
End Sub

Private Sub BT19_Click()
    Call modGameLogic.BT19
End Sub

Private Sub BT20_Click()
    Call modGameLogic.BT20
End Sub

Private Sub BT21_Click()
    Call modGameLogic.BT21
End Sub

Private Sub CheckTur1_Click()
    Call modGameLogic.CheckTur1
End Sub

Private Sub CheckTur10_Click()
    Call modGameLogic.CheckTur10
End Sub

Private Sub CheckTur11_Click()
    Call modGameLogic.CheckTur11
End Sub

Private Sub CheckTur12_Click()
    Call modGameLogic.CheckTur12
End Sub

Private Sub CheckTur13_Click()
    Call modGameLogic.CheckTur13
End Sub

Private Sub CheckTur14_Click()
    Call modGameLogic.CheckTur14
End Sub

Private Sub CheckTur15_Click()
    Call modGameLogic.CheckTur15
End Sub

Private Sub CheckTur16_Click()
    Call modGameLogic.CheckTur16
End Sub

Private Sub CheckTur17_Click()
    Call modGameLogic.CheckTur17
End Sub

Private Sub CheckTur18_Click()
    Call modGameLogic.CheckTur18
End Sub

Private Sub CheckTur19_Click()
    Call modGameLogic.CheckTur19
End Sub

Private Sub CheckTur2_Click()
    Call modGameLogic.CheckTur2
End Sub

Private Sub CheckTur20_Click()
    Call modGameLogic.CheckTur20
End Sub

Private Sub CheckTur21_Click()
    Call modGameLogic.CheckTur21
End Sub

Private Sub CheckTur3_Click()
    Call modGameLogic.CheckTur3
End Sub

Private Sub CheckTur4_Click()
    Call modGameLogic.CheckTur4
End Sub

Private Sub CheckTur5_Click()
    Call modGameLogic.CheckTur5
End Sub

Private Sub CheckTur6_Click()
    Call modGameLogic.CheckTur6
End Sub

Private Sub CheckTur7_Click()
    Call modGameLogic.CheckTur7
End Sub

Private Sub CheckTur8_Click()
    Call modGameLogic.CheckTur8
End Sub

Private Sub CheckTur9_Click()
    Call modGameLogic.CheckTur9
End Sub

Private Sub FireTurret_Click()
    Call modGameLogic.FireTurret
End Sub

Private Sub LaunchRAF_Click()
    Call modGameLogic.LaunchRAF
End Sub

Private Sub MakeRepairs_Click()
    Call modGameLogic.MakeRepairs
End Sub

Private Sub NextTurn_Click()
    Call modGameLogic.NextTurn_Click
End Sub

Private Sub NextWave_Click()
    Call modGameLogic.NextWave_Click
End Sub

Private Sub NextWavePreLaunchDone_Click()
    Call modGameLogic.NextWavePreLaunchDone
End Sub

Private Sub PreLaunchBack_Click()
    Call modGameLogic.PreLaunchBack
End Sub

Private Sub QuitGame_Click()
    Call modGameLogic.QuitGame_Click
End Sub

Private Sub RAFCheckFire_Click()
    Call modGameLogic.RAFCheckFire
End Sub

Private Sub RAFCheckRockets_Click()
    Call modGameLogic.RAFCheckRockets
End Sub

Private Sub RAFCommLaunch_Click()
    Call modGameLogic.RAFCommLaunch
End Sub

Private Sub RAFDirSpin_SpinDown()
    Call modGameLogic.RAFDirSpinLeft
End Sub

Private Sub RAFDirSpin_SpinUp()
    Call modGameLogic.RAFDirSpinRight
End Sub

Private Sub RAFNext_Click()
    Call modGameLogic.RAFNext
End Sub

Private Sub RAFShopPortal_Click()
    Call modGameLogic.RAFShopPortal
End Sub

Private Sub RAFShopReset_Click()
    Call modGameLogic.RAFShopPortal
End Sub

Private Sub RAFSpeSpin_SpinDown()
    Call modGameLogic.RAFSpeSpinLeft
End Sub

Private Sub RAFSpeSpin_SpinUp()
    Call modGameLogic.RAFSpeSpinRight
End Sub

Private Sub RepairsBack_Click()
    Call modGameLogic.RepairsBack
End Sub

Private Sub RepairShopPortal_Click()
    Call modGameLogic.RepairShopPortal
End Sub

Private Sub RocketArm_Click()
    Call modGameLogic.RocketArm
End Sub

Private Sub SkipTurret_Click()
    Call modGameLogic.SkipTurret
End Sub

Private Sub SpinTurretAim_SpinDown()
    Call modGameLogic.SpinTurretAimLeft
End Sub

Private Sub SpinTurretAim_SpinUp()
    Call modGameLogic.SpinTurretAimRight
End Sub

Private Sub SS01_SpinDown()
    Call modGameLogic.SS01Down
End Sub

Private Sub SS01_SpinUp()
    Call modGameLogic.SS01Up
End Sub

Private Sub SS02_SpinDown()
    Call modGameLogic.SS02Down
End Sub

Private Sub SS02_SpinUp()
    Call modGameLogic.SS02Up
End Sub

Private Sub SS03_SpinDown()
    Call modGameLogic.SS03Down
End Sub

Private Sub SS03_SpinUp()
    Call modGameLogic.SS03Up
End Sub

Private Sub SS04_SpinDown()
    Call modGameLogic.SS04Down
End Sub

Private Sub SS04_SpinUp()
    Call modGameLogic.SS04Up
End Sub

Private Sub SS05_SpinDown()
    Call modGameLogic.SS05Down
End Sub

Private Sub SS05_SpinUp()
    Call modGameLogic.SS05Up
End Sub

Private Sub SS06_SpinDown()
    Call modGameLogic.SS06Down
End Sub

Private Sub SS06_SpinUp()
    Call modGameLogic.SS06Up
End Sub

Private Sub SS07_SpinDown()
    Call modGameLogic.SS07Down
End Sub

Private Sub SS07_SpinUp()
    Call modGameLogic.SS07Up
End Sub

Private Sub SS08_SpinDown()
    Call modGameLogic.SS08Down
End Sub

Private Sub SS08_SpinUp()
    Call modGameLogic.SS08Up
End Sub

Private Sub SS09_SpinDown()
    Call modGameLogic.SS09Down
End Sub

Private Sub SS09_SpinUp()
    Call modGameLogic.SS09Up
End Sub

Private Sub SS10_SpinDown()
    Call modGameLogic.SS10Down
End Sub

Private Sub SS10_SpinUp()
    Call modGameLogic.SS10Up
End Sub

Private Sub SS11_SpinDown()
    Call modGameLogic.SS11Down
End Sub

Private Sub SS11_SpinUp()
    Call modGameLogic.SS11Up
End Sub

Private Sub SS12_SpinDown()
    Call modGameLogic.SS12Down
End Sub

Private Sub SS12_SpinUp()
    Call modGameLogic.SS12Up
End Sub

Private Sub SS13_SpinDown()
    Call modGameLogic.SS13Down
End Sub

Private Sub SS13_SpinUp()
    Call modGameLogic.SS13Up
End Sub

Private Sub SS14_SpinDown()
    Call modGameLogic.SS14Down
End Sub

Private Sub SS14_SpinUp()
    Call modGameLogic.SS14Up
End Sub

Private Sub SS15_SpinDown()
    Call modGameLogic.SS15Down
End Sub

Private Sub SS15_SpinUp()
    Call modGameLogic.SS15Up
End Sub

Private Sub SS16_SpinDown()
    Call modGameLogic.SS16Down
End Sub

Private Sub SS16_SpinUp()
    Call modGameLogic.SS16Up
End Sub

Private Sub SS17_SpinDown()
    Call modGameLogic.SS17Down
End Sub

Private Sub SS17_SpinUp()
    Call modGameLogic.SS17Up
End Sub

Private Sub SS18_SpinDown()
    Call modGameLogic.SS18Down
End Sub

Private Sub SS18_SpinUp()
    Call modGameLogic.SS18Up
End Sub

Private Sub SS19_SpinDown()
    Call modGameLogic.SS19Down
End Sub

Private Sub SS19_SpinUp()
    Call modGameLogic.SS19Up
End Sub

Private Sub SS20_SpinDown()
    Call modGameLogic.SS20Down
End Sub

Private Sub SS20_SpinUp()
    Call modGameLogic.SS20Up
End Sub

Private Sub SS21_SpinDown()
    Call modGameLogic.SS21Down
End Sub

Private Sub SS21_SpinUp()
    Call modGameLogic.SS21Up
End Sub

Private Sub ST01_SpinDown()
    Call modGameLogic.ST01Down
End Sub

Private Sub ST01_SpinUp()
    Call modGameLogic.ST01Up
End Sub

Private Sub ST02_SpinDown()
    Call modGameLogic.ST02Down
End Sub

Private Sub ST02_SpinUp()
    Call modGameLogic.ST02Up
End Sub

Private Sub ST03_SpinDown()
    Call modGameLogic.ST03Down
End Sub

Private Sub ST03_SpinUp()
    Call modGameLogic.ST03Up
End Sub

Private Sub ST04_SpinDown()
    Call modGameLogic.ST04Down
End Sub

Private Sub ST04_SpinUp()
    Call modGameLogic.ST04Up
End Sub

Private Sub ST05_SpinDown()
    Call modGameLogic.ST05Down
End Sub

Private Sub ST05_SpinUp()
    Call modGameLogic.ST05Up
End Sub

Private Sub ST06_SpinDown()
    Call modGameLogic.ST06Down
End Sub

Private Sub ST06_SpinUp()
    Call modGameLogic.ST06Up
End Sub

Private Sub ST07_SpinDown()
    Call modGameLogic.ST07Down
End Sub

Private Sub ST07_SpinUp()
    Call modGameLogic.ST07Up
End Sub

Private Sub ST08_SpinDown()
    Call modGameLogic.ST08Down
End Sub

Private Sub ST08_SpinUp()
    Call modGameLogic.ST08Up
End Sub

Private Sub ST09_SpinDown()
    Call modGameLogic.ST09Down
End Sub

Private Sub ST09_SpinUp()
    Call modGameLogic.ST09Up
End Sub

Private Sub ST10_SpinDown()
    Call modGameLogic.ST10Down
End Sub

Private Sub ST10_SpinUp()
    Call modGameLogic.ST10Up
End Sub

Private Sub ST11_SpinDown()
    Call modGameLogic.ST11Down
End Sub

Private Sub ST11_SpinUp()
    Call modGameLogic.ST11Up
End Sub

Private Sub ST12_SpinDown()
    Call modGameLogic.ST12Down
End Sub

Private Sub ST12_SpinUp()
    Call modGameLogic.ST12Up
End Sub

Private Sub ST13_SpinDown()
    Call modGameLogic.ST13Down
End Sub

Private Sub ST13_SpinUp()
    Call modGameLogic.ST13Up
End Sub

Private Sub ST14_SpinDown()
    Call modGameLogic.ST14Down
End Sub

Private Sub ST14_SpinUp()
    Call modGameLogic.ST14Up
End Sub

Private Sub ST15_SpinDown()
    Call modGameLogic.ST15Down
End Sub

Private Sub ST15_SpinUp()
    Call modGameLogic.ST15Up
End Sub

Private Sub ST16_SpinDown()
    Call modGameLogic.ST16Down
End Sub

Private Sub ST16_SpinUp()
    Call modGameLogic.ST16Up
End Sub

Private Sub ST17_SpinDown()
    Call modGameLogic.ST17Down
End Sub

Private Sub ST17_SpinUp()
    Call modGameLogic.ST17Up
End Sub

Private Sub ST18_SpinDown()
    Call modGameLogic.ST18Down
End Sub

Private Sub ST18_SpinUp()
    Call modGameLogic.ST18Up
End Sub

Private Sub ST19_SpinDown()
    Call modGameLogic.ST19Down
End Sub

Private Sub ST19_SpinUp()
    Call modGameLogic.ST19Up
End Sub

Private Sub ST20_SpinDown()
    Call modGameLogic.ST20Down
End Sub

Private Sub ST20_SpinUp()
    Call modGameLogic.ST20Up
End Sub

Private Sub ST21_SpinDown()
    Call modGameLogic.ST21Down
End Sub

Private Sub ST21_SpinUp()
    Call modGameLogic.ST21Up
End Sub

Private Sub StartGame_Click()
    Call modGameLogic.StartGame_Click
End Sub
